version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ubuntu
hooks:
  ApplicationStart:
    - location: scripts/docker-up.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/docker-stop.sh
      timeout: 300
      runas: ubuntu
